version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_ID}/deployment-archive
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: proddeployuser
